//! Gateway Configuration Wizard State
//!
//! Manages the multi-step configuration wizard for BeeBotOS Gateway setup.

use leptos::prelude::*;
use serde::{Deserialize, Serialize};

/// Wizard configuration mode
#[derive(Clone, Debug, Default, PartialEq)]
pub enum WizardMode {
    #[default]
    Fresh,
    Import(String),
    Template(String),
}

/// Validation error for a specific field
#[derive(Clone, Debug, PartialEq)]
pub struct ValidationError {
    pub field: String,
    pub message: String,
}

/// Complete wizard state
#[derive(Clone, Debug, PartialEq)]
pub struct WizardState {
    pub current_step: usize,
    pub mode: WizardMode,
    pub server: ServerConfigDraft,
    pub database: DatabaseConfigDraft,
    pub jwt: JwtConfigDraft,
    pub models: ModelsConfigDraft,
    pub channels: ChannelsConfigDraft,
    pub blockchain: BlockchainConfigDraft,
    pub logging: LoggingConfigDraft,
    pub validation_errors: Vec<ValidationError>,
    pub is_submitting: bool,
    pub toml_preview: String,
    pub env_preview: String,
}

impl Default for WizardState {
    fn default() -> Self {
        Self {
            current_step: 1,
            mode: WizardMode::Fresh,
            server: ServerConfigDraft::default(),
            database: DatabaseConfigDraft::default(),
            jwt: JwtConfigDraft::default(),
            models: ModelsConfigDraft::default(),
            channels: ChannelsConfigDraft::default(),
            blockchain: BlockchainConfigDraft::default(),
            logging: LoggingConfigDraft::default(),
            validation_errors: Vec::new(),
            is_submitting: false,
            toml_preview: String::new(),
            env_preview: String::new(),
        }
    }
}

impl WizardState {
    pub fn can_proceed(&self) -> bool {
        self.validation_errors.is_empty()
    }

    pub fn validate_step(&mut self, step: usize) -> bool {
        self.validation_errors.clear();
        match step {
            2 => self.validate_server(),
            3 => self.validate_database(),
            4 => self.validate_jwt(),
            5 => self.validate_models(),
            6 => self.validate_channels(),
            7 => self.validate_blockchain(),
            8 => self.validate_logging(),
            _ => true,
        }
    }

    fn validate_server(&mut self) -> bool {
        if self.server.host.is_empty() {
            self.validation_errors.push(ValidationError {
                field: "host".to_string(),
                message: "Host is required".to_string(),
            });
        }
        if self.server.http_port == 0 {
            self.validation_errors.push(ValidationError {
                field: "http_port".to_string(),
                message: "HTTP port must be greater than 0".to_string(),
            });
        }
        true // allow proceeding even with warnings
    }

    fn validate_database(&mut self) -> bool {
        if self.database.db_type == "sqlite" && self.database.sqlite_path.is_empty() {
            self.validation_errors.push(ValidationError {
                field: "sqlite_path".to_string(),
                message: "SQLite path is required".to_string(),
            });
        }
        if self.database.db_type == "postgres" && self.database.postgres_url.is_empty() {
            self.validation_errors.push(ValidationError {
                field: "postgres_url".to_string(),
                message: "PostgreSQL URL is required".to_string(),
            });
        }
        true
    }

    fn validate_jwt(&mut self) -> bool {
        if self.jwt.secret.len() < 32 {
            self.validation_errors.push(ValidationError {
                field: "secret".to_string(),
                message: "JWT secret must be at least 32 characters".to_string(),
            });
        }
        true
    }

    fn validate_models(&mut self) -> bool {
        if self.models.providers.is_empty() {
            self.validation_errors.push(ValidationError {
                field: "providers".to_string(),
                message: "At least one LLM provider is required".to_string(),
            });
        }
        true
    }

    fn validate_channels(&mut self) -> bool {
        true
    }

    fn validate_blockchain(&mut self) -> bool {
        true
    }

    fn validate_logging(&mut self) -> bool {
        true
    }

    pub fn generate_toml(&self) -> String {
        let mut s = String::new();
        s.push_str("# BeeBotOS Gateway Configuration\n");
        s.push_str("# Generated by Configuration Wizard\n\n");
        s.push_str("[server]\n");
        s.push_str(&format!("host = \"{}\"\n", self.server.host));
        s.push_str(&format!("http_port = {}\n", self.server.http_port));
        s.push_str(&format!("grpc_port = {}\n", self.server.grpc_port));
        s.push_str(&format!(
            "request_timeout = {}\n",
            self.server.request_timeout
        ));
        s.push_str(&format!("max_body_size = {}\n", self.server.max_body_size));
        s.push_str(&format!(
            "cors_origins = {:?}\n\n",
            self.server.cors_origins
        ));

        s.push_str("[database]\n");
        s.push_str(&format!("db_type = \"{}\"\n", self.database.db_type));
        if self.database.db_type == "sqlite" {
            s.push_str(&format!(
                "sqlite_path = \"{}\"\n",
                self.database.sqlite_path
            ));
        } else {
            s.push_str(&format!(
                "postgres_url = \"{}\"\n",
                self.database.postgres_url
            ));
        }
        s.push_str(&format!(
            "max_connections = {}\n",
            self.database.max_connections
        ));
        s.push_str(&format!(
            "min_connections = {}\n",
            self.database.min_connections
        ));
        s.push_str(&format!(
            "connect_timeout = {}\n",
            self.database.connect_timeout
        ));
        s.push_str(&format!(
            "auto_migrate = {}\n\n",
            self.database.auto_migrate
        ));

        s.push_str("[jwt]\n");
        s.push_str(&format!("secret = \"{}\"\n", self.jwt.secret));
        s.push_str(&format!("token_expiry = {}\n", self.jwt.token_expiry));
        s.push_str(&format!(
            "refresh_token_expiry = {}\n\n",
            self.jwt.refresh_token_expiry
        ));

        s.push_str("[models]\n");
        s.push_str(&format!(
            "default_provider = \"{}\"\n",
            self.models.default_provider
        ));
        s.push_str(&format!(
            "fallback_chain = {:?}\n",
            self.models.fallback_chain
        ));
        s.push_str(&format!(
            "cost_optimization = {}\n",
            self.models.cost_optimization
        ));
        s.push_str(&format!("max_tokens = {}\n", self.models.max_tokens));
        s.push_str(&format!(
            "request_timeout = {}\n\n",
            self.models.request_timeout
        ));

        for provider in &self.models.providers {
            s.push_str(&format!("[models.providers.{}]\n", provider.name));
            s.push_str(&format!("api_key = \"{}\"\n", provider.api_key));
            s.push_str(&format!("model = \"{}\"\n", provider.model));
            s.push_str(&format!("base_url = \"{}\"\n", provider.base_url));
            s.push_str(&format!("temperature = {}\n", provider.temperature));
            if let Some(ctx) = provider.context_window {
                s.push_str(&format!("context_window = {}\n", ctx));
            }
            s.push('\n');
        }

        s.push_str("[blockchain]\n");
        s.push_str(&format!("enabled = {}\n", self.blockchain.enabled));
        if self.blockchain.enabled {
            s.push_str(&format!("chain_id = {}\n", self.blockchain.chain_id));
            s.push_str(&format!("rpc_url = \"{}\"\n", self.blockchain.rpc_url));
        }
        s.push('\n');

        s.push_str("[logging]\n");
        s.push_str(&format!("level = \"{}\"\n", self.logging.level));
        s.push_str(&format!("format = \"{}\"\n", self.logging.format));
        s.push_str(&format!("file_path = \"{}\"\n", self.logging.file_path));
        s.push_str(&format!("rotation = \"{}\"\n", self.logging.rotation));
        s.push_str(&format!(
            "enable_metrics = {}\n",
            self.logging.enable_metrics
        ));
        s.push_str(&format!("metrics_port = {}\n", self.logging.metrics_port));
        s.push_str(&format!(
            "enable_tracing = {}\n",
            self.logging.enable_tracing
        ));
        s.push_str(&format!(
            "otlp_endpoint = \"{}\"\n",
            self.logging.otlp_endpoint
        ));
        s.push_str(&format!(
            "trace_sampling_rate = {}\n",
            self.logging.trace_sampling_rate
        ));

        s
    }

    pub fn generate_env(&self) -> String {
        let mut s = String::new();
        s.push_str("# BeeBotOS Environment Variables\n");
        s.push_str(&format!("BEE__SERVER__HOST={}\n", self.server.host));
        s.push_str(&format!(
            "BEE__SERVER__HTTP_PORT={}\n",
            self.server.http_port
        ));
        s.push_str(&format!(
            "BEE__SERVER__GRPC_PORT={}\n",
            self.server.grpc_port
        ));
        s.push_str(&format!("BEE__DATABASE__TYPE={}\n", self.database.db_type));
        if self.database.db_type == "sqlite" {
            s.push_str(&format!(
                "BEE__DATABASE__SQLITE_PATH={}\n",
                self.database.sqlite_path
            ));
        } else {
            s.push_str(&format!(
                "BEE__DATABASE__POSTGRES_URL={}\n",
                self.database.postgres_url
            ));
        }
        s.push_str(&format!("BEE__JWT__SECRET={}\n", self.jwt.secret));
        s.push_str(&format!(
            "BEE__JWT__TOKEN_EXPIRY={}\n",
            self.jwt.token_expiry
        ));
        s.push_str(&format!(
            "BEE__MODELS__DEFAULT_PROVIDER={}\n",
            self.models.default_provider
        ));
        s.push_str(&format!(
            "BEE__MODELS__MAX_TOKENS={}\n",
            self.models.max_tokens
        ));
        s.push_str(&format!(
            "BEE__BLOCKCHAIN__ENABLED={}\n",
            self.blockchain.enabled
        ));
        s.push_str(&format!("BEE__LOGGING__LEVEL={}\n", self.logging.level));
        s
    }

    pub fn generate_docker_compose(&self) -> String {
        let mut s = String::new();
        s.push_str("version: '3.8'\n\n");
        s.push_str("services:\n");

        // Database service (if postgres)
        if self.database.db_type == "postgres" {
            s.push_str("  postgres:\n");
            s.push_str("    image: postgres:16-alpine\n");
            s.push_str("    container_name: beebotos-postgres\n");
            s.push_str("    environment:\n");
            s.push_str("      - POSTGRES_DB=beebotos\n");
            s.push_str("      - POSTGRES_USER=bee\n");
            s.push_str("      - POSTGRES_PASSWORD=changeme\n");
            s.push_str("    volumes:\n");
            s.push_str("      - postgres_data:/var/lib/postgresql/data\n");
            s.push_str("    ports:\n");
            s.push_str("      - \"5432:5432\"\n");
            s.push_str("    healthcheck:\n");
            s.push_str("      test: [\"CMD-SHELL\", \"pg_isready -U bee\"]\n");
            s.push_str("      interval: 10s\n");
            s.push_str("      timeout: 5s\n");
            s.push_str("      retries: 5\n");
            s.push_str("    restart: unless-stopped\n\n");
        }

        s.push_str("  beebotos-gateway:\n");
        s.push_str("    image: beebotos/gateway:latest\n");
        s.push_str("    container_name: beebotos-gateway\n");
        s.push_str("    ports:\n");
        s.push_str(&format!(
            "      - \"{}:{}\"\n",
            self.server.http_port, self.server.http_port
        ));
        s.push_str(&format!(
            "      - \"{}:{}\"\n",
            self.server.grpc_port, self.server.grpc_port
        ));
        if self.logging.enable_metrics {
            s.push_str(&format!(
                "      - \"{}:{}\"\n",
                self.logging.metrics_port, self.logging.metrics_port
            ));
        }
        s.push_str("    environment:\n");
        s.push_str(&format!("      - BEE__SERVER__HOST={}\n", self.server.host));
        s.push_str(&format!(
            "      - BEE__SERVER__HTTP_PORT={}\n",
            self.server.http_port
        ));
        s.push_str(&format!(
            "      - BEE__SERVER__GRPC_PORT={}\n",
            self.server.grpc_port
        ));
        s.push_str(&format!(
            "      - BEE__DATABASE__TYPE={}\n",
            self.database.db_type
        ));
        if self.database.db_type == "sqlite" {
            s.push_str(&format!(
                "      - BEE__DATABASE__SQLITE_PATH={}\n",
                self.database.sqlite_path
            ));
        } else {
            s.push_str(&format!(
                "      - BEE__DATABASE__POSTGRES_URL={}\n",
                self.database.postgres_url
            ));
        }
        s.push_str(&format!("      - BEE__JWT__SECRET={}\n", self.jwt.secret));
        s.push_str(&format!(
            "      - BEE__JWT__TOKEN_EXPIRY={}\n",
            self.jwt.token_expiry
        ));
        s.push_str(&format!(
            "      - BEE__MODELS__DEFAULT_PROVIDER={}\n",
            self.models.default_provider
        ));
        s.push_str(&format!(
            "      - BEE__MODELS__MAX_TOKENS={}\n",
            self.models.max_tokens
        ));
        s.push_str(&format!(
            "      - BEE__BLOCKCHAIN__ENABLED={}\n",
            self.blockchain.enabled
        ));
        s.push_str(&format!(
            "      - BEE__LOGGING__LEVEL={}\n",
            self.logging.level
        ));
        s.push_str(&format!(
            "      - BEE__LOGGING__ENABLE_METRICS={}\n",
            self.logging.enable_metrics
        ));
        if self.logging.enable_metrics {
            s.push_str(&format!(
                "      - BEE__LOGGING__METRICS_PORT={}\n",
                self.logging.metrics_port
            ));
        }
        s.push_str("    volumes:\n");
        s.push_str("      - ./data:/app/data\n");
        s.push_str("      - ./config:/app/config\n");
        s.push_str("      - ./logs:/app/logs\n");
        if self.database.db_type == "postgres" {
            s.push_str("    depends_on:\n");
            s.push_str("      postgres:\n");
            s.push_str("        condition: service_healthy\n");
        }
        s.push_str("    restart: unless-stopped\n");
        s.push_str("    healthcheck:\n");
        s.push_str("      test: [\"CMD\", \"curl\", \"-f\", \"http://localhost:8000/health\"]\n");
        s.push_str("      interval: 30s\n");
        s.push_str("      timeout: 10s\n");
        s.push_str("      retries: 3\n");

        if self.database.db_type == "postgres" {
            s.push_str("\nvolumes:\n");
            s.push_str("  postgres_data:\n");
        }
        s
    }

    pub fn generate_k8s(&self) -> String {
        let mut s = String::new();

        // ConfigMap for non-sensitive configuration
        s.push_str("apiVersion: v1\n");
        s.push_str("kind: ConfigMap\n");
        s.push_str("metadata:\n");
        s.push_str("  name: beebotos-config\n");
        s.push_str("  labels:\n");
        s.push_str("    app: beebotos-gateway\n");
        s.push_str("data:\n");
        s.push_str(&format!("  BEE__SERVER__HOST: \"{}\"\n", self.server.host));
        s.push_str(&format!(
            "  BEE__SERVER__HTTP_PORT: \"{}\"\n",
            self.server.http_port
        ));
        s.push_str(&format!(
            "  BEE__SERVER__GRPC_PORT: \"{}\"\n",
            self.server.grpc_port
        ));
        s.push_str(&format!(
            "  BEE__DATABASE__TYPE: \"{}\"\n",
            self.database.db_type
        ));
        if self.database.db_type == "sqlite" {
            s.push_str(&format!(
                "  BEE__DATABASE__SQLITE_PATH: \"{}\"\n",
                self.database.sqlite_path
            ));
        }
        s.push_str(&format!(
            "  BEE__MODELS__DEFAULT_PROVIDER: \"{}\"\n",
            self.models.default_provider
        ));
        s.push_str(&format!(
            "  BEE__MODELS__MAX_TOKENS: \"{}\"\n",
            self.models.max_tokens
        ));
        s.push_str(&format!(
            "  BEE__BLOCKCHAIN__ENABLED: \"{}\"\n",
            self.blockchain.enabled
        ));
        s.push_str(&format!(
            "  BEE__LOGGING__LEVEL: \"{}\"\n",
            self.logging.level
        ));
        s.push_str(&format!(
            "  BEE__LOGGING__ENABLE_METRICS: \"{}\"\n",
            self.logging.enable_metrics
        ));
        s.push_str("---\n");

        // Secret for sensitive data
        s.push_str("apiVersion: v1\n");
        s.push_str("kind: Secret\n");
        s.push_str("metadata:\n");
        s.push_str("  name: beebotos-secrets\n");
        s.push_str("  labels:\n");
        s.push_str("    app: beebotos-gateway\n");
        s.push_str("type: Opaque\n");
        s.push_str("stringData:\n");
        s.push_str(&format!("  BEE__JWT__SECRET: \"{}\"\n", self.jwt.secret));
        if self.database.db_type == "postgres" {
            s.push_str(&format!(
                "  BEE__DATABASE__POSTGRES_URL: \"{}\"\n",
                self.database.postgres_url
            ));
        }
        s.push_str("---\n");

        // Deployment
        s.push_str("apiVersion: apps/v1\n");
        s.push_str("kind: Deployment\n");
        s.push_str("metadata:\n");
        s.push_str("  name: beebotos-gateway\n");
        s.push_str("  labels:\n");
        s.push_str("    app: beebotos-gateway\n");
        s.push_str("spec:\n");
        s.push_str("  replicas: 1\n");
        s.push_str("  selector:\n");
        s.push_str("    matchLabels:\n");
        s.push_str("      app: beebotos-gateway\n");
        s.push_str("  template:\n");
        s.push_str("    metadata:\n");
        s.push_str("      labels:\n");
        s.push_str("        app: beebotos-gateway\n");
        s.push_str("    spec:\n");
        s.push_str("      containers:\n");
        s.push_str("      - name: gateway\n");
        s.push_str("        image: beebotos/gateway:latest\n");
        s.push_str("        ports:\n");
        s.push_str(&format!(
            "        - containerPort: {}\n",
            self.server.http_port
        ));
        s.push_str(&format!(
            "        - containerPort: {}\n",
            self.server.grpc_port
        ));
        if self.logging.enable_metrics {
            s.push_str(&format!(
                "        - containerPort: {}\n",
                self.logging.metrics_port
            ));
        }
        s.push_str("        envFrom:\n");
        s.push_str("        - configMapRef:\n");
        s.push_str("            name: beebotos-config\n");
        s.push_str("        - secretRef:\n");
        s.push_str("            name: beebotos-secrets\n");
        s.push_str("        volumeMounts:\n");
        s.push_str("        - name: data\n");
        s.push_str("          mountPath: /app/data\n");
        s.push_str("        - name: logs\n");
        s.push_str("          mountPath: /app/logs\n");
        s.push_str("        livenessProbe:\n");
        s.push_str("          httpGet:\n");
        s.push_str("            path: /health\n");
        s.push_str(&format!("            port: {}\n", self.server.http_port));
        s.push_str("          initialDelaySeconds: 30\n");
        s.push_str("          periodSeconds: 30\n");
        s.push_str("        readinessProbe:\n");
        s.push_str("          httpGet:\n");
        s.push_str("            path: /health\n");
        s.push_str(&format!("            port: {}\n", self.server.http_port));
        s.push_str("          initialDelaySeconds: 5\n");
        s.push_str("          periodSeconds: 10\n");
        s.push_str("      volumes:\n");
        s.push_str("      - name: data\n");
        s.push_str("        emptyDir: {}\n");
        s.push_str("      - name: logs\n");
        s.push_str("        emptyDir: {}\n");
        s.push_str("---\n");

        // Service
        s.push_str("apiVersion: v1\n");
        s.push_str("kind: Service\n");
        s.push_str("metadata:\n");
        s.push_str("  name: beebotos-gateway\n");
        s.push_str("spec:\n");
        s.push_str("  selector:\n");
        s.push_str("    app: beebotos-gateway\n");
        s.push_str("  ports:\n");
        s.push_str(&format!(
            "  - port: {}\n    targetPort: {}\n    name: http\n",
            self.server.http_port, self.server.http_port
        ));
        s.push_str(&format!(
            "  - port: {}\n    targetPort: {}\n    name: grpc\n",
            self.server.grpc_port, self.server.grpc_port
        ));
        if self.logging.enable_metrics {
            s.push_str(&format!(
                "  - port: {}\n    targetPort: {}\n    name: metrics\n",
                self.logging.metrics_port, self.logging.metrics_port
            ));
        }
        s.push_str("  type: ClusterIP\n");

        // Ingress (optional)
        s.push_str("---\n");
        s.push_str("apiVersion: networking.k8s.io/v1\n");
        s.push_str("kind: Ingress\n");
        s.push_str("metadata:\n");
        s.push_str("  name: beebotos-gateway\n");
        s.push_str("  annotations:\n");
        s.push_str("    nginx.ingress.kubernetes.io/rewrite-target: /\n");
        s.push_str("spec:\n");
        s.push_str("  rules:\n");
        s.push_str("  - host: beebotos.local\n");
        s.push_str("    http:\n");
        s.push_str("      paths:\n");
        s.push_str("      - path: /\n");
        s.push_str("        pathType: Prefix\n");
        s.push_str("        backend:\n");
        s.push_str("          service:\n");
        s.push_str("            name: beebotos-gateway\n");
        s.push_str(&format!("            port:\n"));
        s.push_str(&format!(
            "              number: {}\n",
            self.server.http_port
        ));
        s
    }

    pub fn apply_template(&mut self, template: &str) {
        match template {
            "minimal" => {
                self.server = ServerConfigDraft {
                    host: "0.0.0.0".to_string(),
                    http_port: 8000,
                    grpc_port: 50051,
                    cors_origins: vec!["*".to_string()],
                    request_timeout: 30,
                    max_body_size: 10,
                    tls_enabled: false,
                    tls_cert_path: String::new(),
                    tls_key_path: String::new(),
                    mtls_enabled: false,
                };
                self.database = DatabaseConfigDraft {
                    db_type: "sqlite".to_string(),
                    sqlite_path: "data/beebotos.db".to_string(),
                    postgres_url: String::new(),
                    max_connections: 10,
                    min_connections: 2,
                    connect_timeout: 30,
                    auto_migrate: true,
                };
                self.models = ModelsConfigDraft {
                    default_provider: "kimi".to_string(),
                    fallback_chain: vec!["kimi".to_string()],
                    cost_optimization: false,
                    max_tokens: 4096,
                    request_timeout: 60,
                    system_prompt: "You are a helpful assistant.".to_string(),
                    providers: vec![ProviderDraft {
                        name: "kimi".to_string(),
                        api_key: String::new(),
                        model: "moonshot-v1-8k".to_string(),
                        base_url: "https://api.moonshot.cn".to_string(),
                        temperature: 0.7,
                        context_window: Some(8192),
                    }],
                };
                self.channels = ChannelsConfigDraft {
                    auto_download_media: true,
                    max_file_size: 50,
                    context_window: 20,
                    auto_reply: true,
                    default_agent_id: "agent-001".to_string(),
                    platforms: vec![
                        PlatformDraft {
                            name: "webchat".to_string(),
                            enabled: true,
                            settings: std::collections::HashMap::new(),
                        },
                        PlatformDraft {
                            name: "lark".to_string(),
                            enabled: true,
                            settings: std::collections::HashMap::new(),
                        },
                    ],
                };
                self.logging = LoggingConfigDraft {
                    level: "info".to_string(),
                    format: "json".to_string(),
                    file_path: "logs/beebotos.log".to_string(),
                    rotation: "daily".to_string(),
                    enable_metrics: true,
                    metrics_port: 9090,
                    enable_tracing: false,
                    otlp_endpoint: "http://localhost:4317".to_string(),
                    trace_sampling_rate: 0.1,
                };
            }
            "standard" => {
                self.apply_template("minimal");
                self.models.fallback_chain = vec![
                    "kimi".to_string(),
                    "openai".to_string(),
                    "deepseek".to_string(),
                ];
                self.models.providers = vec![
                    ProviderDraft {
                        name: "kimi".to_string(),
                        api_key: String::new(),
                        model: "moonshot-v1-8k".to_string(),
                        base_url: "https://api.moonshot.cn".to_string(),
                        temperature: 0.7,
                        context_window: Some(8192),
                    },
                    ProviderDraft {
                        name: "openai".to_string(),
                        api_key: String::new(),
                        model: "gpt-4".to_string(),
                        base_url: "https://api.openai.com/v1".to_string(),
                        temperature: 0.7,
                        context_window: Some(8192),
                    },
                    ProviderDraft {
                        name: "deepseek".to_string(),
                        api_key: String::new(),
                        model: "deepseek-chat".to_string(),
                        base_url: "https://api.deepseek.com".to_string(),
                        temperature: 0.7,
                        context_window: Some(8192),
                    },
                ];
                self.channels.platforms = vec![
                    PlatformDraft {
                        name: "webchat".to_string(),
                        enabled: true,
                        settings: std::collections::HashMap::new(),
                    },
                    PlatformDraft {
                        name: "lark".to_string(),
                        enabled: true,
                        settings: std::collections::HashMap::new(),
                    },
                    PlatformDraft {
                        name: "telegram".to_string(),
                        enabled: true,
                        settings: std::collections::HashMap::new(),
                    },
                    PlatformDraft {
                        name: "dingtalk".to_string(),
                        enabled: false,
                        settings: std::collections::HashMap::new(),
                    },
                    PlatformDraft {
                        name: "discord".to_string(),
                        enabled: false,
                        settings: std::collections::HashMap::new(),
                    },
                ];
            }
            "enterprise" => {
                self.apply_template("standard");
                self.database = DatabaseConfigDraft {
                    db_type: "postgres".to_string(),
                    sqlite_path: String::new(),
                    postgres_url: "postgres://user:pass@localhost/beebotos".to_string(),
                    max_connections: 50,
                    min_connections: 5,
                    connect_timeout: 30,
                    auto_migrate: true,
                };
                self.server.tls_enabled = true;
                self.logging.enable_tracing = true;
            }
            _ => {}
        }
    }
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct ServerConfigDraft {
    pub host: String,
    pub http_port: u16,
    pub grpc_port: u16,
    pub cors_origins: Vec<String>,
    pub request_timeout: u64,
    pub max_body_size: u64,
    pub tls_enabled: bool,
    pub tls_cert_path: String,
    pub tls_key_path: String,
    pub mtls_enabled: bool,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct DatabaseConfigDraft {
    pub db_type: String,
    pub sqlite_path: String,
    pub postgres_url: String,
    pub max_connections: u32,
    pub min_connections: u32,
    pub connect_timeout: u64,
    pub auto_migrate: bool,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct JwtConfigDraft {
    pub secret: String,
    pub token_expiry: u64,
    pub refresh_token_expiry: u64,
    pub rate_limit_enabled: bool,
    pub qps_limit: u32,
    pub burst_limit: u32,
    pub webhook_ip_whitelist: Vec<String>,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct ModelsConfigDraft {
    pub default_provider: String,
    pub fallback_chain: Vec<String>,
    pub cost_optimization: bool,
    pub max_tokens: u32,
    pub system_prompt: String,
    pub request_timeout: u64,
    pub providers: Vec<ProviderDraft>,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct ProviderDraft {
    pub name: String,
    pub api_key: String,
    pub model: String,
    pub base_url: String,
    pub temperature: f32,
    pub context_window: Option<u32>,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct ChannelsConfigDraft {
    pub auto_download_media: bool,
    pub max_file_size: u64,
    pub context_window: u32,
    pub auto_reply: bool,
    pub default_agent_id: String,
    pub platforms: Vec<PlatformDraft>,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct PlatformDraft {
    pub name: String,
    pub enabled: bool,
    pub settings: std::collections::HashMap<String, String>,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct BlockchainConfigDraft {
    pub enabled: bool,
    pub chain_id: u64,
    pub rpc_url: String,
    pub contract_addresses: std::collections::HashMap<String, String>,
    pub wallet_mnemonic: String,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct LoggingConfigDraft {
    pub level: String,
    pub format: String,
    pub file_path: String,
    pub rotation: String,
    pub enable_metrics: bool,
    pub metrics_port: u16,
    pub enable_tracing: bool,
    pub otlp_endpoint: String,
    pub trace_sampling_rate: f64,
}

/// Generate a random JWT secret
pub fn generate_jwt_secret() -> Result<String, String> {
    let mut bytes = [0u8; 32];
    let window = web_sys::window().ok_or("Window not available".to_string())?;
    let crypto = window
        .crypto()
        .map_err(|_| "Crypto API not available".to_string())?;
    crypto
        .get_random_values_with_u8_array(&mut bytes)
        .map_err(|_| "Failed to generate random values".to_string())?;
    let mut hex = String::with_capacity(64);
    for b in bytes {
        hex.push_str(&format!("{:02x}", b));
    }
    Ok(hex)
}

/// Provide wizard state in context
pub fn provide_wizard_state() {
    provide_context(RwSignal::new(WizardState::default()));
}

/// Use the wizard state from context
pub fn use_wizard_state() -> RwSignal<WizardState> {
    use_context::<RwSignal<WizardState>>().expect("WizardState not provided")
}
